language: python
python:
- '3.6'
- 3.7-dev
env:
  secure: SEuqwJGjetaPwakFQ7tIrjvY0RGrSDYKDmlDHr8m4RfWa8eiBibQ2USfUvffv39Lg2ZnOFj2sagAMfJZRsdrQrZIXirUj/LT17ei8kw+ObrcCyECcL9HAFFUYG/utitnUNlxKa2l67lQ2FLc7BaIBZOrw6Bem/SCkWRnWSfQaDdl0Da8cAbR4JfzeBLqFeT4GyErf6gKJx1yXXHNF6rzj/ehL2MtnwkdxEkj9zexASCu8gCXZXQSxhBRzTGI3BzoFeEATqY8NzzpBbFjMHCg00QDPTEjOZ1Oz1uMko/g1FgjxQeXoZ5M3FSRr/VXHxAnxDKdeCL3e99ZlwQPHLyib+dJxCfVnj7YdzSNdvFb8OnBNPouMBPClJ5P75dVAuT6zPkc2trAkxpz5c/qUCuDKGUEetivYuG7BAULWh6xzq4GyQvMcioMUD+2ABmAtVhANOtyywP3DhWabr8xPPXUl8zBnXjq57BCeSCVUzq/SnDhEUs0PdSr71vA3kG/l06dJUYfaF7VTSTD4MSV9wnWqnjkihklY0SPG8WdaeNpre7t0CWeLNwALTAKsxVrXOLF+eGNeCGfwBqm+Y9DSuy4H/6w4psd5fkC5N+F/KzhyG3hHPWMWv38tFgroLgxcub6NPQ4wC3C5c8b5OcYDU5SHx4cCKg1EYgyiQeMVXjSQ4g=
install:
- pip install -U pycodestyle
- pip install -U setuptools
- python setup.py install
script:
- pycodestyle --max-line-length=100 starred
- starred --username maguowei --sort
deploy:
  provider: pypi
  user: maguowei
  password:
    secure: VtyBZ4HNueTl0o6snZPpc2kuSwgdAspSAWPWuV57eh8ZWPZZgRXwfIllbJD62Yz5JZfZ2H94CmAca+f8Thmb+oHwE2g6llbMyAP7mQQlHhTYkfpb01uCVJYgAnpbr5ngJrqj79NBWU+Vzxa4qCAjMNLUxJjkDpBJUK+/XDm8z9jNS0ZDWilOjBOB1c2ionjp/p9aAYUvVO2VnVhhlL7Q3ZCU/S91STJkH7hwMog/EyHBRk7t7Y/IkhdyBMfzUm6nC9xsMRMbON8mPY0dYI9ukg2y7dv9PEW8qshA1NS9Xh7RUpRfr2eU/Wh6Sjf8YxTVEReMWD80aYNOL+AysIFduFlp8sAIxrw9OAFFaj5MjXFs2+GfeuxnEoGsSlhNOIlh3wErA1YXENCqeFBG+17UkWZ/tiyS4cPcIUyYDjWON65ErZl3Xo+AFVt9VIG7F1I1K+0BYmv1OO8OlfhUZxW2j4PfmQa2qMw0KBurlj4zAM5OyeT8Piy8ehwLquh/nWkYr6OVRU38VuJZ9GbjmyqkdfrOu2kn9ZF0hGI/Sh1IWOI0rJ6Uslfw7U4OolLGb8G0Vlp4JgLkvM/SSypVi8W11qkrheVl0sQfwXa51B59RjlMFbneabtNyKS3YUpD0g17HrGzkXuYRUrbIDqyAiJf5wtgmrXjgJagbUv7wJKCgBc=
  on:
    tags: true
    repo: maguowei/starred
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: P+gYlhDfPcAKl5M9TRF739NaRkYgoQ6u6rJjRghH0H1cWQcRfCHzzbQNxAIcxJqWpBUAFTnZMGl1WdrbuV19n/AIoFX7ZZiV4kqSMYKHUrVfGyD1IBdvsvR7/SoMEWB1I6rlrw8yQyrdHigp6A0yg1zUl706TCEVJKDZuqnqeQHBHfwyxrGX8tmCTiPnw1JJQzzpUyppPrwBTjrurOBwUN79eNm/ONxyZGkhJdYGEkXeLZM7FUPMMushmHjv9DzLfa0zoh0szeqm51kDWbtfnJF/upV4pXv/iVx0PDavJ5pnh5eK5FAQInqcEJxS4/xHQrQiq5AlSs8TzSD9wwWedBwspn9+fe2ebCUdAfRgdxQPpS2xOHcgFKQ3YS+v5JDKfjKKGEOnlvfjtq/KgaBHXzMZPOAzFRQDC0m886E7vuKgeYH7QyflCD3es6k42EmXkMgUKIzMYOtWI2tx78OlZ4T/Tyn98f0/wOJUzKkyqQk6jnV6xcK4nDkF6f4aZm1qgJoauItbex9sLDeC1tuFZ14e94cShnqX7VLOMUkhERJN0bOfUiU3P0JEPJRW/UbAWQC5PtFpngcTNWUzc5Jm84L94s+9d3ADK7Y6rrKanKONIQVtFxWu/wa3+a2MAR73FGnz81OAWSdY0+z6WbpiqhNW9oKL+R/olmuwNh8z/fo=
