language: python
python:
- '2.7'
- '3.5'
- '3.6'
env:
  secure: SEuqwJGjetaPwakFQ7tIrjvY0RGrSDYKDmlDHr8m4RfWa8eiBibQ2USfUvffv39Lg2ZnOFj2sagAMfJZRsdrQrZIXirUj/LT17ei8kw+ObrcCyECcL9HAFFUYG/utitnUNlxKa2l67lQ2FLc7BaIBZOrw6Bem/SCkWRnWSfQaDdl0Da8cAbR4JfzeBLqFeT4GyErf6gKJx1yXXHNF6rzj/ehL2MtnwkdxEkj9zexASCu8gCXZXQSxhBRzTGI3BzoFeEATqY8NzzpBbFjMHCg00QDPTEjOZ1Oz1uMko/g1FgjxQeXoZ5M3FSRr/VXHxAnxDKdeCL3e99ZlwQPHLyib+dJxCfVnj7YdzSNdvFb8OnBNPouMBPClJ5P75dVAuT6zPkc2trAkxpz5c/qUCuDKGUEetivYuG7BAULWh6xzq4GyQvMcioMUD+2ABmAtVhANOtyywP3DhWabr8xPPXUl8zBnXjq57BCeSCVUzq/SnDhEUs0PdSr71vA3kG/l06dJUYfaF7VTSTD4MSV9wnWqnjkihklY0SPG8WdaeNpre7t0CWeLNwALTAKsxVrXOLF+eGNeCGfwBqm+Y9DSuy4H/6w4psd5fkC5N+F/KzhyG3hHPWMWv38tFgroLgxcub6NPQ4wC3C5c8b5OcYDU5SHx4cCKg1EYgyiQeMVXjSQ4g=
install:
- pip install -U pycodestyle
- python setup.py install
script:
- pycodestyle --max-line-length=100 starred.py
- starred --username maguowei --sort
deploy:
  provider: pypi
  user: maguowei
  password:
    secure: Bg/KoDc8AZ5YnBw/tw8zRXbXij6uuy3azpiVVsPSGyaMlL5pDpXx/qPo8x5vdoMlK12uKE12WugGhO8ti0TTPAnIOgLRFZ+8VLxDdkDzdnW78ObQry7CSM/6TQv/KrgPZUFIugUr9rT2xq3vcXvCtWC4EJlbSmYKCIb3F4zeCr3S5Pk8yRBla6AMrKS2LDmlD86XCTjY9s1KLadqs9/bzxZMkBnOYxOn1F8/ksianMB8L0NjqZASv5Kn04c1icKSqV0zFSQ4oJm3v7d6VP+hABo4Yj75WjsifmHB6DqaYoelt6RG/A5DKqrnsiqP12hvjOfY2G0lAbtt6/xXLCh14V/GjQ7sDqMcKEJSVl7ox6QoTnM/DhrHPQLBvyQJ0FFG+1CWdEZzCDLl/PY/P6mUeK1SSzwrXQmHWdYmYJGHGgy74R2pEG2T0h0oDmuCGVK1hpShDGYCyTPvMMXvciGbhVQ0NzUuy39G5ZFv+AyYpAtAWogkBXopI/T/exc3JnSvbQWfLyVn7A+UUc8lcrHz1DaD8Wn3pHogJv5awNqrswF7RJc40TEPhfokppcdFGPNrmCpdHDtiui6+Hu2JoP2a8J42eQY8SMJ5CQHE/eR8tCEtnQhsel9q6xZQ+W36+GhZmRLv5OruIkRPmYgAg/10wO5DE6f9QKf4XVuflC0+UI=
  on:
    tags: true
    repo: maguowei/starred
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: P+gYlhDfPcAKl5M9TRF739NaRkYgoQ6u6rJjRghH0H1cWQcRfCHzzbQNxAIcxJqWpBUAFTnZMGl1WdrbuV19n/AIoFX7ZZiV4kqSMYKHUrVfGyD1IBdvsvR7/SoMEWB1I6rlrw8yQyrdHigp6A0yg1zUl706TCEVJKDZuqnqeQHBHfwyxrGX8tmCTiPnw1JJQzzpUyppPrwBTjrurOBwUN79eNm/ONxyZGkhJdYGEkXeLZM7FUPMMushmHjv9DzLfa0zoh0szeqm51kDWbtfnJF/upV4pXv/iVx0PDavJ5pnh5eK5FAQInqcEJxS4/xHQrQiq5AlSs8TzSD9wwWedBwspn9+fe2ebCUdAfRgdxQPpS2xOHcgFKQ3YS+v5JDKfjKKGEOnlvfjtq/KgaBHXzMZPOAzFRQDC0m886E7vuKgeYH7QyflCD3es6k42EmXkMgUKIzMYOtWI2tx78OlZ4T/Tyn98f0/wOJUzKkyqQk6jnV6xcK4nDkF6f4aZm1qgJoauItbex9sLDeC1tuFZ14e94cShnqX7VLOMUkhERJN0bOfUiU3P0JEPJRW/UbAWQC5PtFpngcTNWUzc5Jm84L94s+9d3ADK7Y6rrKanKONIQVtFxWu/wa3+a2MAR73FGnz81OAWSdY0+z6WbpiqhNW9oKL+R/olmuwNh8z/fo=
